### ISSUE TITLE
Trying to get this to work, but getting a json error in Ruby.

### ISSUE THREAD

**Issue by schatt** [roylez/alfred_taskwarrior#1]
When I try to run the ruby manually, I get the following:

[schatt@Drews-MBP:user.workflow.527E237D-8AD0-4E67-9E43-D0E33E5F83A4]12:37pm-5052 % ruby main.rb ls
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/json/common.rb:155:in `parse': 399: unexpected token at ',{"id":1,"description":"Book flights to Mexico","due":"20160322T070000Z","entry":"20160321T064018Z","modified":"20160321T065736Z","project":"Wedding","status":"pending","uuid":"7a849ca2-3cf1-462a-a91d-b338f45c8c59","urgency":9.58327},,{"id":4,"description":"Go to get bp med prescription","due":"20160321T070000Z","entry":"20160321T065644Z","modified":"20160321T065813Z","project":"Medical","status":"pending","uuid":"fdc56777-9833-4b2d-b140-044a451c36fd","urgency":18.0404},,{"id":5,"depends":"fdc56777-9833-4b2d-b140-044a451c36fd","description":"Dropoff\/Pickup prescriptions from CVS","due":"20160321T070000Z","entry":"20160321T065714Z","modified":"20160321T070641Z","project":"Medical","status":"pending","uuid":"d9f0b657-6358-4959-8f6f-b7a9c4b2eef6","urgency":5.04041},,{"id":6,"description":"Track down missing ssh packets to new vpn.","due":"20160322T070000Z","entry":"20160321T190832Z","modified":"20160321T190832Z","project":"Fonality","status":"pending","uuid":"0c567f88-ca7d-4a03-a4cc-36f43988a56a","urgency":9.58327},]]' (JSON::ParserError)
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/json/common.rb:155:in`parse'
    from /Users/schatt/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.527E237D-8AD0-4E67-9E43-D0E33E5F83A4/taskwarrior.rb:17:in `json'
    from /Users/schatt/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.527E237D-8AD0-4E67-9E43-D0E33E5F83A4/taskwarrior.rb:21:in`export'
    from main.rb:74:in `<main>'

**Comment by roylez** [comment]
f15a7a7 fixes the issue. New version of taskwarrior changes its export format.
